apiVersion: apps/v1
kind: Deployment
metadata:
  name: fullstack-deployment
spec:
  selector:
    matchLabels:
      app: fullstack
  replicas: 3
  template:
    metadata:
      labels:
        app: fullstack
    spec:
      containers:
      - name: fullstack
        image: manojkrishnappa/fullstack:14092024
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: fullstack-ssvc
spec:
  selector:
    app: fullstack
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  type: LoadBalancer
